version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/banco:/var/lib/mysql
    restart: always
