version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ROOT_HOST: '%'
      # MYSQL_USER: ${MYSQL_APP_USER}
      # MYSQL_PASSWORD: ${MYSQL_APP_PASSWORD}
      TZ: "America/Manaus"
    command: --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/banco:/var/lib/mysql
    restart: always
